
server:
  port: 8761

#http://localhost:8091/h2-console

  Spring:
    h2:
      console:
        enable: true

# linea de conexion
#cada microservicio debe tener su base de datos
        datasource:
        url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
        driverClassName: org.h2.Driver
        platform: h2
        username: sa
        password:

    jpa:
      show-sql:true                      #jpa nos permite que mapee nuestra base de datos y se actualice al entorno que se esta trabajando
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: false
          format_sql: false
          logging:
            pattern:
              console:"%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


